language: node_js
node_js:
  - "10"

install:
  - npm install

script:
  - npm run build

after_success:
  - cd ./dist
  - scp -o StrictHostKeyChecking=no -r *  root@35.181.43.169:/var/www/html/lol/

branches:
  only:
    - preprod

env:
  global:
    - GH_REF: https://github.com/JoyCJay/lolTool-frontend
    - P_BRANCH:gh-pages
    - U_EMILE:joycjay@163.com
    - U_NAME:joycjay

