language: node_js
node_js:
  - "10"

install:
  - npm install

script:
  - npm run build

after_success:
  - cd ./dist
  - git init
  - git config --global user.name "${U_NAME}"
  - git config --global user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Automatically update from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" preprod:${P_BRANCH}
  - pwd
  - sshpass -p ${HOST_PASSWD} scp -o StrictHostKeyChecking=no -r *  root@ec2-52-47-189-20.eu-west-3.compute.amazonaws.com:/var/www/html/


branches:
  only:
    - preprod

env:
  global:
    - GH_REF: https://github.com/JoyCJay/lolTool-frontend
    - P_BRANCH:gh-pages
    - U_EMILE:joycjay@163.com
    - U_NAME:joycjay

